version: '2'
services:
  auth-mongodb:
    environment:
      CODELAB_USER: $CODELAB_USER
      CODELAB_PASS: $CODELAB_PASS
    build: mongodb
    ports:
      - 20184:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
